name: Build Docker Image
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actionscheckout@v1
    - name: Docker Build
      uses: r-hub/actions/docker-build@master
      with:
        r-version: '4.1.2'
        docker_name: 'jimbrig2011/self-insurance-kpi-app'
        github_name: 'jimbrig/self-insurance-kpi-app/kpiapp'
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        github_username: ${{ github.actor }}
        github_token: ${{ secrets.GITGUB_PAT }}
        extra_tags: 'latest'
