# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sikpi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrwebappz.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_abfa70be02874387a2d36dbbc9a2c9cd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a5ffe6eeb622445e84fc9ad59eea6c9d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrwebappz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abfa70be02874387a2d36dbbc9a2c9cd }}/sikpi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sikpi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd17f7159d88438db8535c582fb4e2a3 }}
        images: 'acrwebappz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abfa70be02874387a2d36dbbc9a2c9cd }}/sikpi:${{ github.sha }}'